// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type HandlersAcceptPortalInviteRequest = {
    password: string;
    token: string;
};

export type HandlersAdvanceOnboardingRequest = {
    step: number;
};

export type HandlersAuthResponse = {
    access_token?: string;
    coach?: ModelsCoach;
    refresh_token?: string;
};

export type HandlersCreateCheckInRequest = {
    energy_score?: number;
    hip_inches?: number;
    mood_score?: number;
    notes?: string;
    photo_urls?: Array<string>;
    sleep_hrs?: number;
    waist_inches?: number;
    week_start_date: string;
    weight_lbs?: number;
};

export type HandlersCreateClientRequest = {
    dietary_preference?: string;
    email: string;
    first_name: string;
    goal: string;
    goal_sub?: string;
    last_name: string;
    phone?: string;
    plan_name?: string;
    plan_price_cents?: number;
    program_total?: number;
    program_week?: number;
    send_invite?: boolean;
    start_date: string;
    status?: 'active' | 'paused' | 'new' | 'ended' | 'trial';
    target_weight_lbs?: number;
};

export type HandlersCreateInvoiceRequest = {
    amount_cents: number;
    client_id?: string;
    /**
     * Currency: any 3-char string. We normalize to lowercase server-side
     * (see below), so a `lowercase` validator tag here would reject the
     * input before normalization could lift it.
     */
    currency?: string;
    description?: string;
    due_date?: string;
};

export type HandlersCreateSessionRequest = {
    client_id?: string;
    confirmed?: boolean;
    duration_mins?: number;
    google_event_id?: string;
    notes?: string;
    session_type: 'virtual' | 'inperson' | 'group';
    starts_at: string;
    title?: string;
    zoom_link?: string;
};

export type HandlersInviteClientPortalResponse = {
    expires_at?: string;
    /**
     * raw; coach's frontend emails this to the client
     */
    invite_token?: string;
    /**
     * ready-to-use deep link to the accept-invite page
     */
    invite_url?: string;
};

export type HandlersListCheckInsResponse = {
    check_ins?: Array<ModelsCoachCheckIn>;
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListClientsResponse = {
    clients?: Array<ModelsClient>;
    /**
     * 1-indexed
     */
    page?: number;
    per_page?: number;
    /**
     * total rows matching filters, ignoring pagination
     */
    total?: number;
    total_pages?: number;
};

export type HandlersListNotificationsResponse = {
    notifications?: Array<ModelsNotification>;
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPaymentsResponse = {
    page?: number;
    payments?: Array<ModelsCoachPayment>;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPortalCheckInsResponse = {
    check_ins?: Array<ModelsCheckIn>;
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPortalPaymentsResponse = {
    page?: number;
    payments?: Array<ModelsPayment>;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPortalSessionsResponse = {
    page?: number;
    per_page?: number;
    sessions?: Array<ModelsSession>;
    total?: number;
    total_pages?: number;
};

export type HandlersListSessionsResponse = {
    page?: number;
    per_page?: number;
    sessions?: Array<ModelsCoachSession>;
    total?: number;
    total_pages?: number;
};

export type HandlersLoginRequest = {
    email: string;
    password: string;
};

export type HandlersLogoutRequest = {
    refresh_token: string;
};

export type HandlersPortalAuthResponse = {
    access_token?: string;
    client_id?: string;
    coach_id?: string;
    email?: string;
    refresh_token?: string;
};

export type HandlersPortalLoginRequest = {
    email: string;
    password: string;
};

export type HandlersPortalLogoutRequest = {
    refresh_token: string;
};

export type HandlersPortalMeResponse = {
    /**
     * Client identity
     */
    client_id?: string;
    coach_avatar?: string;
    coach_bio?: string;
    coach_business?: string;
    /**
     * Coach mini-profile
     */
    coach_id?: string;
    coach_name?: string;
    email?: string;
    first_name?: string;
    /**
     * Program
     */
    goal?: string;
    goal_sub?: string;
    last_name?: string;
    phone?: string;
    plan_name?: string;
    program_total?: number;
    program_week?: number;
    /**
     * YYYY-MM-DD
     */
    start_date?: string;
    status?: string;
};

export type HandlersPortalRefreshRequest = {
    refresh_token: string;
};

export type HandlersRefreshRequest = {
    refresh_token: string;
};

export type HandlersReplaceCustomQuestionsRequest = {
    questions?: Array<ModelsCustomQuestion>;
};

export type HandlersRespondToCheckInRequest = {
    response: string;
};

export type HandlersSaveCheckInDraftRequest = {
    draft?: string;
};

export type HandlersSignupRequest = {
    email: string;
    first_name: string;
    last_name: string;
    password: string;
    specialty: 'personal-training' | 'online-coaching' | 'nutrition' | 'studio';
};

export type HandlersSlugCheckResponse = {
    available?: boolean;
    slug?: string;
};

export type HandlersUnreadCountResponse = {
    count?: number;
};

export type HandlersUpdateAvailabilitySlot = {
    day_of_week?: number;
    enabled?: boolean;
    end_time: string;
    start_time: string;
};

export type HandlersUpdateClientRequest = {
    dietary_preference?: string;
    email?: string;
    first_name?: string;
    goal?: string;
    goal_sub?: string;
    last_name?: string;
    phone?: string;
    plan_name?: string;
    plan_price_cents?: number;
    program_total?: number;
    program_week?: number;
    start_date?: string;
    status?: 'active' | 'paused' | 'new' | 'ended' | 'trial';
    target_weight_lbs?: number;
};

export type HandlersUpdateMeRequest = {
    avatar_url?: string;
    bio?: string;
    business_name?: string;
    first_name?: string;
    last_name?: string;
    slug?: string;
    specialty?: 'personal-training' | 'online-coaching' | 'nutrition' | 'studio';
};

export type HandlersUpdateMyAvailabilityRequest = {
    slots: Array<HandlersUpdateAvailabilitySlot>;
};

export type HandlersUpdateMySettingsRequest = {
    buffer_mins?: number;
    checkin_days?: Array<number>;
    checkin_deadline?: string;
    max_sessions_per_day?: number;
    min_notice_hrs?: number;
    notif_checkin_new?: boolean;
    notif_checkin_overdue?: boolean;
    notif_checkin_streak?: boolean;
    notif_payment_failed?: boolean;
    notif_payment_received?: boolean;
    notif_schedule_change?: boolean;
    notif_schedule_digest?: boolean;
    reminder_hours?: number;
    timezone?: string;
};

export type HandlersUpdatePaymentRequest = {
    description?: string;
    due_date?: string;
    paid_at?: string;
    sent_at?: string;
    status?: 'paid' | 'pending' | 'failed' | 'overdue' | 'active' | 'cancelling';
};

export type HandlersUpdatePortalMeRequest = {
    phone?: string;
};

export type HandlersUpdateSessionRequest = {
    confirmed?: boolean;
    duration_mins?: number;
    google_event_id?: string;
    notes?: string;
    session_type?: 'virtual' | 'inperson' | 'group';
    starts_at?: string;
    title?: string;
    zoom_link?: string;
};

export type HandlersWsTicketResponse = {
    expires_at?: string;
    ticket?: string;
};

export type ModelsAppError = {
    code?: string;
    error?: string;
};

export type ModelsCheckIn = {
    client_id?: string;
    coach_id?: string;
    coach_response?: string;
    created_at?: string;
    energy_score?: number;
    hip_inches?: number;
    id?: string;
    is_read?: boolean;
    mood_score?: number;
    notes?: string;
    photo_urls?: Array<string>;
    responded_at?: string;
    sleep_hrs?: number;
    submitted_at?: string;
    waist_inches?: number;
    /**
     * YYYY-MM-DD (Monday)
     */
    week_start_date?: string;
    weight_lbs?: number;
};

export type ModelsClient = {
    coach_id?: string;
    created_at?: string;
    dietary_preference?: string;
    email?: string;
    first_name?: string;
    goal?: string;
    goal_sub?: string;
    id?: string;
    last_check_in?: string;
    last_name?: string;
    phone?: string;
    plan_name?: string;
    plan_price_cents?: number;
    program_total?: number;
    program_week?: number;
    sessions_count?: number;
    /**
     * YYYY-MM-DD
     */
    start_date?: string;
    status?: string;
    streak_weeks?: number;
    target_weight_lbs?: number;
    updated_at?: string;
};

export type ModelsCoach = {
    avatar_url?: string;
    bio?: string;
    business_name?: string;
    created_at?: string;
    email?: string;
    first_name?: string;
    id?: string;
    last_name?: string;
    onboarding_done?: boolean;
    onboarding_step?: number;
    plan?: string;
    plan_seat_limit?: number;
    slug?: string;
    specialty?: string;
    updated_at?: string;
};

export type ModelsCoachAvailabilitySlot = {
    coach_id?: string;
    day_of_week?: number;
    enabled?: boolean;
    /**
     * "HH:MM"
     */
    end_time?: string;
    id?: string;
    /**
     * "HH:MM"
     */
    start_time?: string;
};

export type ModelsCoachCheckIn = {
    client_id?: string;
    coach_id?: string;
    coach_response?: string;
    created_at?: string;
    energy_score?: number;
    hip_inches?: number;
    id?: string;
    is_read?: boolean;
    mood_score?: number;
    notes?: string;
    photo_urls?: Array<string>;
    responded_at?: string;
    response_draft?: string;
    sleep_hrs?: number;
    submitted_at?: string;
    waist_inches?: number;
    /**
     * YYYY-MM-DD (Monday)
     */
    week_start_date?: string;
    weight_lbs?: number;
};

export type ModelsCoachPayment = {
    amount_cents?: number;
    client_id?: string;
    coach_id?: string;
    created_at?: string;
    currency?: string;
    description?: string;
    /**
     * YYYY-MM-DD
     */
    due_date?: string;
    id?: string;
    invoice_number?: string;
    /**
     * YYYY-MM-DD
     */
    next_billing_date?: string;
    paid_at?: string;
    payment_type?: string;
    sent_at?: string;
    status?: string;
    stripe_invoice_id?: string;
    stripe_sub_id?: string;
    updated_at?: string;
};

export type ModelsCoachSession = {
    client_id?: string;
    coach_id?: string;
    confirmed?: boolean;
    created_at?: string;
    duration_mins?: number;
    google_event_id?: string;
    id?: string;
    notes?: string;
    session_type?: string;
    starts_at?: string;
    title?: string;
    updated_at?: string;
    zoom_link?: string;
};

export type ModelsCoachSettings = {
    buffer_mins?: number;
    /**
     * 0=Sun .. 6=Sat
     */
    checkin_days?: Array<number>;
    /**
     * "HH:MM" 24h
     */
    checkin_deadline?: string;
    coach_id?: string;
    custom_questions?: Array<ModelsCustomQuestion>;
    max_sessions_per_day?: number;
    min_notice_hrs?: number;
    notif_checkin_new?: boolean;
    notif_checkin_overdue?: boolean;
    notif_checkin_streak?: boolean;
    notif_payment_failed?: boolean;
    notif_payment_received?: boolean;
    notif_schedule_change?: boolean;
    notif_schedule_digest?: boolean;
    reminder_hours?: number;
    timezone?: string;
    updated_at?: string;
};

export type ModelsCustomQuestion = {
    id: string;
    label: string;
    required?: boolean;
    type: 'text' | 'number' | 'scale' | 'boolean';
};

export type ModelsDashboardStats = {
    active_clients?: number;
    checkins_this_week?: number;
    sessions_today?: number;
    unread_checkins?: number;
};

export type ModelsNotification = {
    created_at?: string;
    /**
     * `swaggertype:"object"` tells swag to document this as an opaque JSON
     * object. The actual Go type is json.RawMessage so the embedded event
     * payload passes through verbatim — the schema is event-type-specific
     * and intentionally polymorphic at the wire level.
     */
    data?: {
        [key: string]: unknown;
    };
    id?: string;
    read_at?: string;
    type?: string;
};

export type ModelsPayment = {
    amount_cents?: number;
    client_id?: string;
    coach_id?: string;
    created_at?: string;
    currency?: string;
    description?: string;
    /**
     * YYYY-MM-DD
     */
    due_date?: string;
    id?: string;
    invoice_number?: string;
    /**
     * YYYY-MM-DD
     */
    next_billing_date?: string;
    paid_at?: string;
    payment_type?: string;
    sent_at?: string;
    status?: string;
    updated_at?: string;
};

export type ModelsSession = {
    client_id?: string;
    coach_id?: string;
    confirmed?: boolean;
    created_at?: string;
    duration_mins?: number;
    id?: string;
    notes?: string;
    session_type?: string;
    starts_at?: string;
    title?: string;
    updated_at?: string;
    zoom_link?: string;
};

export type GetApiV1AuthGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google';
};

export type GetApiV1AuthGoogleErrors = {
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type GetApiV1AuthGoogleError = GetApiV1AuthGoogleErrors[keyof GetApiV1AuthGoogleErrors];

export type GetApiV1AuthGoogleCallbackData = {
    body?: never;
    path?: never;
    query: {
        /**
         * OAuth state echoed back by Google
         */
        state: string;
        /**
         * OAuth authorization code
         */
        code: string;
    };
    url: '/api/v1/auth/google/callback';
};

export type GetApiV1AuthGoogleCallbackErrors = {
    /**
     * missing code or state, or state mismatch
     */
    400: ModelsAppError;
    /**
     * google rejected the code
     */
    401: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type GetApiV1AuthGoogleCallbackError = GetApiV1AuthGoogleCallbackErrors[keyof GetApiV1AuthGoogleCallbackErrors];

export type PostApiV1AuthLoginData = {
    /**
     * login payload
     */
    body: HandlersLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * validation failed
     */
    400: ModelsAppError;
    /**
     * invalid credentials
     */
    401: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * OK
     */
    200: HandlersAuthResponse;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthLogoutData = {
    /**
     * logout payload
     */
    body: HandlersLogoutRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type PostApiV1AuthRefreshData = {
    /**
     * refresh payload
     */
    body: HandlersRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * invalid or revoked refresh token
     */
    401: ModelsAppError;
};

export type PostApiV1AuthRefreshError = PostApiV1AuthRefreshErrors[keyof PostApiV1AuthRefreshErrors];

export type PostApiV1AuthRefreshResponses = {
    /**
     * OK
     */
    200: HandlersAuthResponse;
};

export type PostApiV1AuthRefreshResponse = PostApiV1AuthRefreshResponses[keyof PostApiV1AuthRefreshResponses];

export type PostApiV1AuthSignupData = {
    /**
     * signup payload
     */
    body: HandlersSignupRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup';
};

export type PostApiV1AuthSignupErrors = {
    /**
     * validation failed
     */
    400: ModelsAppError;
    /**
     * email already registered
     */
    409: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiV1AuthSignupError = PostApiV1AuthSignupErrors[keyof PostApiV1AuthSignupErrors];

export type PostApiV1AuthSignupResponses = {
    /**
     * Created
     */
    201: HandlersAuthResponse;
};

export type PostApiV1AuthSignupResponse = PostApiV1AuthSignupResponses[keyof PostApiV1AuthSignupResponses];

export type GetApiV1CheckInsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to one client
         */
        client_id?: string;
        /**
         * unread | responded | pending
         */
        status?: string;
        /**
         * YYYY-MM-DD (Monday)
         */
        week_start?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/check-ins';
};

export type GetApiV1CheckInsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1CheckInsError = GetApiV1CheckInsErrors[keyof GetApiV1CheckInsErrors];

export type GetApiV1CheckInsResponses = {
    /**
     * OK
     */
    200: HandlersListCheckInsResponse;
};

export type GetApiV1CheckInsResponse = GetApiV1CheckInsResponses[keyof GetApiV1CheckInsResponses];

export type GetApiV1CheckInsByIdData = {
    body?: never;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/check-ins/{id}';
};

export type GetApiV1CheckInsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1CheckInsByIdError = GetApiV1CheckInsByIdErrors[keyof GetApiV1CheckInsByIdErrors];

export type GetApiV1CheckInsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type GetApiV1CheckInsByIdResponse = GetApiV1CheckInsByIdResponses[keyof GetApiV1CheckInsByIdResponses];

export type PatchApiV1CheckInsByIdDraftData = {
    /**
     * draft payload
     */
    body: HandlersSaveCheckInDraftRequest;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/check-ins/{id}/draft';
};

export type PatchApiV1CheckInsByIdDraftErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PatchApiV1CheckInsByIdDraftError = PatchApiV1CheckInsByIdDraftErrors[keyof PatchApiV1CheckInsByIdDraftErrors];

export type PatchApiV1CheckInsByIdDraftResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type PatchApiV1CheckInsByIdDraftResponse = PatchApiV1CheckInsByIdDraftResponses[keyof PatchApiV1CheckInsByIdDraftResponses];

export type PostApiV1CheckInsByIdReadData = {
    body?: never;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/check-ins/{id}/read';
};

export type PostApiV1CheckInsByIdReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiV1CheckInsByIdReadError = PostApiV1CheckInsByIdReadErrors[keyof PostApiV1CheckInsByIdReadErrors];

export type PostApiV1CheckInsByIdReadResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type PostApiV1CheckInsByIdReadResponse = PostApiV1CheckInsByIdReadResponses[keyof PostApiV1CheckInsByIdReadResponses];

export type PostApiV1CheckInsByIdRespondData = {
    /**
     * response payload
     */
    body: HandlersRespondToCheckInRequest;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/check-ins/{id}/respond';
};

export type PostApiV1CheckInsByIdRespondErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiV1CheckInsByIdRespondError = PostApiV1CheckInsByIdRespondErrors[keyof PostApiV1CheckInsByIdRespondErrors];

export type PostApiV1CheckInsByIdRespondResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type PostApiV1CheckInsByIdRespondResponse = PostApiV1CheckInsByIdRespondResponses[keyof PostApiV1CheckInsByIdRespondResponses];

export type GetApiV1ClientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * active | paused | new | ended
         */
        status?: string;
        /**
         * substring match on name or email
         */
        search?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/clients';
};

export type GetApiV1ClientsErrors = {
    /**
     * invalid query params
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type GetApiV1ClientsError = GetApiV1ClientsErrors[keyof GetApiV1ClientsErrors];

export type GetApiV1ClientsResponses = {
    /**
     * OK
     */
    200: HandlersListClientsResponse;
};

export type GetApiV1ClientsResponse = GetApiV1ClientsResponses[keyof GetApiV1ClientsResponses];

export type PostApiV1ClientsData = {
    /**
     * client to create
     */
    body: HandlersCreateClientRequest;
    path?: never;
    query?: never;
    url: '/api/v1/clients';
};

export type PostApiV1ClientsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * email already in use for this coach
     */
    409: ModelsAppError;
};

export type PostApiV1ClientsError = PostApiV1ClientsErrors[keyof PostApiV1ClientsErrors];

export type PostApiV1ClientsResponses = {
    /**
     * Created
     */
    201: ModelsClient;
};

export type PostApiV1ClientsResponse = PostApiV1ClientsResponses[keyof PostApiV1ClientsResponses];

export type DeleteApiV1ClientsByIdData = {
    body?: never;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/clients/{id}';
};

export type DeleteApiV1ClientsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiV1ClientsByIdError = DeleteApiV1ClientsByIdErrors[keyof DeleteApiV1ClientsByIdErrors];

export type DeleteApiV1ClientsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiV1ClientsByIdResponse = DeleteApiV1ClientsByIdResponses[keyof DeleteApiV1ClientsByIdResponses];

export type GetApiV1ClientsByIdData = {
    body?: never;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/clients/{id}';
};

export type GetApiV1ClientsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1ClientsByIdError = GetApiV1ClientsByIdErrors[keyof GetApiV1ClientsByIdErrors];

export type GetApiV1ClientsByIdResponses = {
    /**
     * OK
     */
    200: ModelsClient;
};

export type GetApiV1ClientsByIdResponse = GetApiV1ClientsByIdResponses[keyof GetApiV1ClientsByIdResponses];

export type PatchApiV1ClientsByIdData = {
    /**
     * fields to change
     */
    body: HandlersUpdateClientRequest;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/clients/{id}';
};

export type PatchApiV1ClientsByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
    /**
     * Conflict
     */
    409: ModelsAppError;
};

export type PatchApiV1ClientsByIdError = PatchApiV1ClientsByIdErrors[keyof PatchApiV1ClientsByIdErrors];

export type PatchApiV1ClientsByIdResponses = {
    /**
     * OK
     */
    200: ModelsClient;
};

export type PatchApiV1ClientsByIdResponse = PatchApiV1ClientsByIdResponses[keyof PatchApiV1ClientsByIdResponses];

export type PostApiV1ClientsByIdInvitePortalData = {
    body?: never;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/clients/{id}/invite-portal';
};

export type PostApiV1ClientsByIdInvitePortalErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiV1ClientsByIdInvitePortalError = PostApiV1ClientsByIdInvitePortalErrors[keyof PostApiV1ClientsByIdInvitePortalErrors];

export type PostApiV1ClientsByIdInvitePortalResponses = {
    /**
     * OK
     */
    200: HandlersInviteClientPortalResponse;
};

export type PostApiV1ClientsByIdInvitePortalResponse = PostApiV1ClientsByIdInvitePortalResponses[keyof PostApiV1ClientsByIdInvitePortalResponses];

export type GetApiV1MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetApiV1MeErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1MeError = GetApiV1MeErrors[keyof GetApiV1MeErrors];

export type GetApiV1MeResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type GetApiV1MeResponse = GetApiV1MeResponses[keyof GetApiV1MeResponses];

export type PatchApiV1MeData = {
    /**
     * fields to change
     */
    body: HandlersUpdateMeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type PatchApiV1MeErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * slug already in use
     */
    409: ModelsAppError;
};

export type PatchApiV1MeError = PatchApiV1MeErrors[keyof PatchApiV1MeErrors];

export type PatchApiV1MeResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type PatchApiV1MeResponse = PatchApiV1MeResponses[keyof PatchApiV1MeResponses];

export type GetApiV1MeAvailabilityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/availability';
};

export type GetApiV1MeAvailabilityErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1MeAvailabilityError = GetApiV1MeAvailabilityErrors[keyof GetApiV1MeAvailabilityErrors];

export type GetApiV1MeAvailabilityResponses = {
    /**
     * OK
     */
    200: Array<ModelsCoachAvailabilitySlot>;
};

export type GetApiV1MeAvailabilityResponse = GetApiV1MeAvailabilityResponses[keyof GetApiV1MeAvailabilityResponses];

export type PutApiV1MeAvailabilityData = {
    /**
     * slots payload
     */
    body: HandlersUpdateMyAvailabilityRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/availability';
};

export type PutApiV1MeAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PutApiV1MeAvailabilityError = PutApiV1MeAvailabilityErrors[keyof PutApiV1MeAvailabilityErrors];

export type PutApiV1MeAvailabilityResponses = {
    /**
     * OK
     */
    200: Array<ModelsCoachAvailabilitySlot>;
};

export type PutApiV1MeAvailabilityResponse = PutApiV1MeAvailabilityResponses[keyof PutApiV1MeAvailabilityResponses];

export type PostApiV1MeAvatarData = {
    body: {
        /**
         * Image file (JPEG/PNG/WEBP, max 4 MB)
         */
        avatar: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/avatar';
};

export type PostApiV1MeAvatarErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Service Unavailable
     */
    503: ModelsAppError;
};

export type PostApiV1MeAvatarError = PostApiV1MeAvatarErrors[keyof PostApiV1MeAvatarErrors];

export type PostApiV1MeAvatarResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type PostApiV1MeAvatarResponse = PostApiV1MeAvatarResponses[keyof PostApiV1MeAvatarResponses];

export type GetApiV1MeDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/dashboard';
};

export type GetApiV1MeDashboardErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1MeDashboardError = GetApiV1MeDashboardErrors[keyof GetApiV1MeDashboardErrors];

export type GetApiV1MeDashboardResponses = {
    /**
     * OK
     */
    200: ModelsDashboardStats;
};

export type GetApiV1MeDashboardResponse = GetApiV1MeDashboardResponses[keyof GetApiV1MeDashboardResponses];

export type PatchApiV1MeOnboardingData = {
    /**
     * step payload
     */
    body: HandlersAdvanceOnboardingRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/onboarding';
};

export type PatchApiV1MeOnboardingErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PatchApiV1MeOnboardingError = PatchApiV1MeOnboardingErrors[keyof PatchApiV1MeOnboardingErrors];

export type PatchApiV1MeOnboardingResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type PatchApiV1MeOnboardingResponse = PatchApiV1MeOnboardingResponses[keyof PatchApiV1MeOnboardingResponses];

export type GetApiV1MeSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/settings';
};

export type GetApiV1MeSettingsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1MeSettingsError = GetApiV1MeSettingsErrors[keyof GetApiV1MeSettingsErrors];

export type GetApiV1MeSettingsResponses = {
    /**
     * OK
     */
    200: ModelsCoachSettings;
};

export type GetApiV1MeSettingsResponse = GetApiV1MeSettingsResponses[keyof GetApiV1MeSettingsResponses];

export type PatchApiV1MeSettingsData = {
    /**
     * fields to change
     */
    body: HandlersUpdateMySettingsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/settings';
};

export type PatchApiV1MeSettingsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PatchApiV1MeSettingsError = PatchApiV1MeSettingsErrors[keyof PatchApiV1MeSettingsErrors];

export type PatchApiV1MeSettingsResponses = {
    /**
     * OK
     */
    200: ModelsCoachSettings;
};

export type PatchApiV1MeSettingsResponse = PatchApiV1MeSettingsResponses[keyof PatchApiV1MeSettingsResponses];

export type PutApiV1MeSettingsCustomQuestionsData = {
    /**
     * questions array
     */
    body: HandlersReplaceCustomQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/settings/custom-questions';
};

export type PutApiV1MeSettingsCustomQuestionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PutApiV1MeSettingsCustomQuestionsError = PutApiV1MeSettingsCustomQuestionsErrors[keyof PutApiV1MeSettingsCustomQuestionsErrors];

export type PutApiV1MeSettingsCustomQuestionsResponses = {
    /**
     * OK
     */
    200: ModelsCoachSettings;
};

export type PutApiV1MeSettingsCustomQuestionsResponse = PutApiV1MeSettingsCustomQuestionsResponses[keyof PutApiV1MeSettingsCustomQuestionsResponses];

export type GetApiV1MeSlugCheckData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Slug to check (3–64 chars)
         */
        slug: string;
    };
    url: '/api/v1/me/slug-check';
};

export type GetApiV1MeSlugCheckErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1MeSlugCheckError = GetApiV1MeSlugCheckErrors[keyof GetApiV1MeSlugCheckErrors];

export type GetApiV1MeSlugCheckResponses = {
    /**
     * OK
     */
    200: HandlersSlugCheckResponse;
};

export type GetApiV1MeSlugCheckResponse = GetApiV1MeSlugCheckResponses[keyof GetApiV1MeSlugCheckResponses];

export type GetApiV1NotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to unread only
         */
        unread?: boolean;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/notifications';
};

export type GetApiV1NotificationsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1NotificationsError = GetApiV1NotificationsErrors[keyof GetApiV1NotificationsErrors];

export type GetApiV1NotificationsResponses = {
    /**
     * OK
     */
    200: HandlersListNotificationsResponse;
};

export type GetApiV1NotificationsResponse = GetApiV1NotificationsResponses[keyof GetApiV1NotificationsResponses];

export type PostApiV1NotificationsMarkAllReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/mark-all-read';
};

export type PostApiV1NotificationsMarkAllReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiV1NotificationsMarkAllReadError = PostApiV1NotificationsMarkAllReadErrors[keyof PostApiV1NotificationsMarkAllReadErrors];

export type PostApiV1NotificationsMarkAllReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1NotificationsMarkAllReadResponse = PostApiV1NotificationsMarkAllReadResponses[keyof PostApiV1NotificationsMarkAllReadResponses];

export type GetApiV1NotificationsUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/unread-count';
};

export type GetApiV1NotificationsUnreadCountErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1NotificationsUnreadCountError = GetApiV1NotificationsUnreadCountErrors[keyof GetApiV1NotificationsUnreadCountErrors];

export type GetApiV1NotificationsUnreadCountResponses = {
    /**
     * OK
     */
    200: HandlersUnreadCountResponse;
};

export type GetApiV1NotificationsUnreadCountResponse = GetApiV1NotificationsUnreadCountResponses[keyof GetApiV1NotificationsUnreadCountResponses];

export type DeleteApiV1NotificationsByIdData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/notifications/{id}';
};

export type DeleteApiV1NotificationsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiV1NotificationsByIdError = DeleteApiV1NotificationsByIdErrors[keyof DeleteApiV1NotificationsByIdErrors];

export type DeleteApiV1NotificationsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiV1NotificationsByIdResponse = DeleteApiV1NotificationsByIdResponses[keyof DeleteApiV1NotificationsByIdResponses];

export type PostApiV1NotificationsByIdReadData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/notifications/{id}/read';
};

export type PostApiV1NotificationsByIdReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiV1NotificationsByIdReadError = PostApiV1NotificationsByIdReadErrors[keyof PostApiV1NotificationsByIdReadErrors];

export type PostApiV1NotificationsByIdReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1NotificationsByIdReadResponse = PostApiV1NotificationsByIdReadResponses[keyof PostApiV1NotificationsByIdReadResponses];

export type GetApiV1PaymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to one client
         */
        client_id?: string;
        /**
         * invoice | subscription
         */
        payment_type?: string;
        /**
         * paid | pending | failed | overdue | active | cancelling
         */
        status?: string;
        /**
         * RFC3339 lower bound (inclusive)
         */
        from?: string;
        /**
         * RFC3339 upper bound (exclusive)
         */
        to?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/payments';
};

export type GetApiV1PaymentsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1PaymentsError = GetApiV1PaymentsErrors[keyof GetApiV1PaymentsErrors];

export type GetApiV1PaymentsResponses = {
    /**
     * OK
     */
    200: HandlersListPaymentsResponse;
};

export type GetApiV1PaymentsResponse = GetApiV1PaymentsResponses[keyof GetApiV1PaymentsResponses];

export type PostApiV1PaymentsData = {
    /**
     * invoice to create
     */
    body: HandlersCreateInvoiceRequest;
    path?: never;
    query?: never;
    url: '/api/v1/payments';
};

export type PostApiV1PaymentsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * client_id not owned by this coach
     */
    404: ModelsAppError;
};

export type PostApiV1PaymentsError = PostApiV1PaymentsErrors[keyof PostApiV1PaymentsErrors];

export type PostApiV1PaymentsResponses = {
    /**
     * Created
     */
    201: ModelsCoachPayment;
};

export type PostApiV1PaymentsResponse = PostApiV1PaymentsResponses[keyof PostApiV1PaymentsResponses];

export type GetApiV1PaymentsByIdData = {
    body?: never;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/payments/{id}';
};

export type GetApiV1PaymentsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1PaymentsByIdError = GetApiV1PaymentsByIdErrors[keyof GetApiV1PaymentsByIdErrors];

export type GetApiV1PaymentsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachPayment;
};

export type GetApiV1PaymentsByIdResponse = GetApiV1PaymentsByIdResponses[keyof GetApiV1PaymentsByIdResponses];

export type PatchApiV1PaymentsByIdData = {
    /**
     * fields to change
     */
    body: HandlersUpdatePaymentRequest;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/payments/{id}';
};

export type PatchApiV1PaymentsByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PatchApiV1PaymentsByIdError = PatchApiV1PaymentsByIdErrors[keyof PatchApiV1PaymentsByIdErrors];

export type PatchApiV1PaymentsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachPayment;
};

export type PatchApiV1PaymentsByIdResponse = PatchApiV1PaymentsByIdResponses[keyof PatchApiV1PaymentsByIdResponses];

export type PostApiV1PaymentsByIdMarkPaidData = {
    body?: never;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/payments/{id}/mark-paid';
};

export type PostApiV1PaymentsByIdMarkPaidErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiV1PaymentsByIdMarkPaidError = PostApiV1PaymentsByIdMarkPaidErrors[keyof PostApiV1PaymentsByIdMarkPaidErrors];

export type PostApiV1PaymentsByIdMarkPaidResponses = {
    /**
     * OK
     */
    200: ModelsCoachPayment;
};

export type PostApiV1PaymentsByIdMarkPaidResponse = PostApiV1PaymentsByIdMarkPaidResponses[keyof PostApiV1PaymentsByIdMarkPaidResponses];

export type PostApiV1PortalAcceptInviteData = {
    /**
     * accept invite payload
     */
    body: HandlersAcceptPortalInviteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/portal/accept-invite';
};

export type PostApiV1PortalAcceptInviteErrors = {
    /**
     * invalid token, expired, or weak password
     */
    400: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiV1PortalAcceptInviteError = PostApiV1PortalAcceptInviteErrors[keyof PostApiV1PortalAcceptInviteErrors];

export type PostApiV1PortalAcceptInviteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1PortalAcceptInviteResponse = PostApiV1PortalAcceptInviteResponses[keyof PostApiV1PortalAcceptInviteResponses];

export type PostApiV1PortalAuthLoginData = {
    /**
     * login payload
     */
    body: HandlersPortalLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/portal/auth/login';
};

export type PostApiV1PortalAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * invalid credentials
     */
    401: ModelsAppError;
};

export type PostApiV1PortalAuthLoginError = PostApiV1PortalAuthLoginErrors[keyof PostApiV1PortalAuthLoginErrors];

export type PostApiV1PortalAuthLoginResponses = {
    /**
     * OK
     */
    200: HandlersPortalAuthResponse;
};

export type PostApiV1PortalAuthLoginResponse = PostApiV1PortalAuthLoginResponses[keyof PostApiV1PortalAuthLoginResponses];

export type PostApiV1PortalAuthLogoutData = {
    /**
     * logout payload
     */
    body: HandlersPortalLogoutRequest;
    path?: never;
    query?: never;
    url: '/api/v1/portal/auth/logout';
};

export type PostApiV1PortalAuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
};

export type PostApiV1PortalAuthLogoutError = PostApiV1PortalAuthLogoutErrors[keyof PostApiV1PortalAuthLogoutErrors];

export type PostApiV1PortalAuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1PortalAuthLogoutResponse = PostApiV1PortalAuthLogoutResponses[keyof PostApiV1PortalAuthLogoutResponses];

export type PostApiV1PortalAuthRefreshData = {
    /**
     * refresh payload
     */
    body: HandlersPortalRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/portal/auth/refresh';
};

export type PostApiV1PortalAuthRefreshErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiV1PortalAuthRefreshError = PostApiV1PortalAuthRefreshErrors[keyof PostApiV1PortalAuthRefreshErrors];

export type PostApiV1PortalAuthRefreshResponses = {
    /**
     * OK
     */
    200: HandlersPortalAuthResponse;
};

export type PostApiV1PortalAuthRefreshResponse = PostApiV1PortalAuthRefreshResponses[keyof PostApiV1PortalAuthRefreshResponses];

export type GetApiV1PortalCheckInsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/portal/check-ins';
};

export type GetApiV1PortalCheckInsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1PortalCheckInsError = GetApiV1PortalCheckInsErrors[keyof GetApiV1PortalCheckInsErrors];

export type GetApiV1PortalCheckInsResponses = {
    /**
     * OK
     */
    200: HandlersListPortalCheckInsResponse;
};

export type GetApiV1PortalCheckInsResponse = GetApiV1PortalCheckInsResponses[keyof GetApiV1PortalCheckInsResponses];

export type PostApiV1PortalCheckInsData = {
    /**
     * check-in payload
     */
    body: HandlersCreateCheckInRequest;
    path?: never;
    query?: never;
    url: '/api/v1/portal/check-ins';
};

export type PostApiV1PortalCheckInsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * check-in for this week already exists
     */
    409: ModelsAppError;
};

export type PostApiV1PortalCheckInsError = PostApiV1PortalCheckInsErrors[keyof PostApiV1PortalCheckInsErrors];

export type PostApiV1PortalCheckInsResponses = {
    /**
     * Created
     */
    201: ModelsCheckIn;
};

export type PostApiV1PortalCheckInsResponse = PostApiV1PortalCheckInsResponses[keyof PostApiV1PortalCheckInsResponses];

export type GetApiV1PortalCheckInsByIdData = {
    body?: never;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/portal/check-ins/{id}';
};

export type GetApiV1PortalCheckInsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1PortalCheckInsByIdError = GetApiV1PortalCheckInsByIdErrors[keyof GetApiV1PortalCheckInsByIdErrors];

export type GetApiV1PortalCheckInsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCheckIn;
};

export type GetApiV1PortalCheckInsByIdResponse = GetApiV1PortalCheckInsByIdResponses[keyof GetApiV1PortalCheckInsByIdResponses];

export type GetApiV1PortalMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/me';
};

export type GetApiV1PortalMeErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1PortalMeError = GetApiV1PortalMeErrors[keyof GetApiV1PortalMeErrors];

export type GetApiV1PortalMeResponses = {
    /**
     * OK
     */
    200: HandlersPortalMeResponse;
};

export type GetApiV1PortalMeResponse = GetApiV1PortalMeResponses[keyof GetApiV1PortalMeResponses];

export type PatchApiV1PortalMeData = {
    /**
     * fields to update
     */
    body: HandlersUpdatePortalMeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/portal/me';
};

export type PatchApiV1PortalMeErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PatchApiV1PortalMeError = PatchApiV1PortalMeErrors[keyof PatchApiV1PortalMeErrors];

export type PatchApiV1PortalMeResponses = {
    /**
     * OK
     */
    200: HandlersPortalMeResponse;
};

export type PatchApiV1PortalMeResponse = PatchApiV1PortalMeResponses[keyof PatchApiV1PortalMeResponses];

export type GetApiV1PortalNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to unread only
         */
        unread?: boolean;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/portal/notifications';
};

export type GetApiV1PortalNotificationsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1PortalNotificationsError = GetApiV1PortalNotificationsErrors[keyof GetApiV1PortalNotificationsErrors];

export type GetApiV1PortalNotificationsResponses = {
    /**
     * OK
     */
    200: HandlersListNotificationsResponse;
};

export type GetApiV1PortalNotificationsResponse = GetApiV1PortalNotificationsResponses[keyof GetApiV1PortalNotificationsResponses];

export type PostApiV1PortalNotificationsMarkAllReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/notifications/mark-all-read';
};

export type PostApiV1PortalNotificationsMarkAllReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiV1PortalNotificationsMarkAllReadError = PostApiV1PortalNotificationsMarkAllReadErrors[keyof PostApiV1PortalNotificationsMarkAllReadErrors];

export type PostApiV1PortalNotificationsMarkAllReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1PortalNotificationsMarkAllReadResponse = PostApiV1PortalNotificationsMarkAllReadResponses[keyof PostApiV1PortalNotificationsMarkAllReadResponses];

export type GetApiV1PortalNotificationsUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/notifications/unread-count';
};

export type GetApiV1PortalNotificationsUnreadCountErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1PortalNotificationsUnreadCountError = GetApiV1PortalNotificationsUnreadCountErrors[keyof GetApiV1PortalNotificationsUnreadCountErrors];

export type GetApiV1PortalNotificationsUnreadCountResponses = {
    /**
     * OK
     */
    200: HandlersUnreadCountResponse;
};

export type GetApiV1PortalNotificationsUnreadCountResponse = GetApiV1PortalNotificationsUnreadCountResponses[keyof GetApiV1PortalNotificationsUnreadCountResponses];

export type DeleteApiV1PortalNotificationsByIdData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/portal/notifications/{id}';
};

export type DeleteApiV1PortalNotificationsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiV1PortalNotificationsByIdError = DeleteApiV1PortalNotificationsByIdErrors[keyof DeleteApiV1PortalNotificationsByIdErrors];

export type DeleteApiV1PortalNotificationsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiV1PortalNotificationsByIdResponse = DeleteApiV1PortalNotificationsByIdResponses[keyof DeleteApiV1PortalNotificationsByIdResponses];

export type PostApiV1PortalNotificationsByIdReadData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/portal/notifications/{id}/read';
};

export type PostApiV1PortalNotificationsByIdReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiV1PortalNotificationsByIdReadError = PostApiV1PortalNotificationsByIdReadErrors[keyof PostApiV1PortalNotificationsByIdReadErrors];

export type PostApiV1PortalNotificationsByIdReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1PortalNotificationsByIdReadResponse = PostApiV1PortalNotificationsByIdReadResponses[keyof PostApiV1PortalNotificationsByIdReadResponses];

export type GetApiV1PortalPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/portal/payments';
};

export type GetApiV1PortalPaymentsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1PortalPaymentsError = GetApiV1PortalPaymentsErrors[keyof GetApiV1PortalPaymentsErrors];

export type GetApiV1PortalPaymentsResponses = {
    /**
     * OK
     */
    200: HandlersListPortalPaymentsResponse;
};

export type GetApiV1PortalPaymentsResponse = GetApiV1PortalPaymentsResponses[keyof GetApiV1PortalPaymentsResponses];

export type GetApiV1PortalPaymentsByIdData = {
    body?: never;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/portal/payments/{id}';
};

export type GetApiV1PortalPaymentsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1PortalPaymentsByIdError = GetApiV1PortalPaymentsByIdErrors[keyof GetApiV1PortalPaymentsByIdErrors];

export type GetApiV1PortalPaymentsByIdResponses = {
    /**
     * OK
     */
    200: ModelsPayment;
};

export type GetApiV1PortalPaymentsByIdResponse = GetApiV1PortalPaymentsByIdResponses[keyof GetApiV1PortalPaymentsByIdResponses];

export type GetApiV1PortalSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * RFC3339 lower bound (inclusive)
         */
        from?: string;
        /**
         * RFC3339 upper bound (exclusive)
         */
        to?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/portal/sessions';
};

export type GetApiV1PortalSessionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1PortalSessionsError = GetApiV1PortalSessionsErrors[keyof GetApiV1PortalSessionsErrors];

export type GetApiV1PortalSessionsResponses = {
    /**
     * OK
     */
    200: HandlersListPortalSessionsResponse;
};

export type GetApiV1PortalSessionsResponse = GetApiV1PortalSessionsResponses[keyof GetApiV1PortalSessionsResponses];

export type GetApiV1PortalSessionsByIdData = {
    body?: never;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/portal/sessions/{id}';
};

export type GetApiV1PortalSessionsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1PortalSessionsByIdError = GetApiV1PortalSessionsByIdErrors[keyof GetApiV1PortalSessionsByIdErrors];

export type GetApiV1PortalSessionsByIdResponses = {
    /**
     * OK
     */
    200: ModelsSession;
};

export type GetApiV1PortalSessionsByIdResponse = GetApiV1PortalSessionsByIdResponses[keyof GetApiV1PortalSessionsByIdResponses];

export type PostApiV1PortalUploadsPhotoData = {
    body: {
        /**
         * Image file (JPEG/PNG/WEBP, max 4 MB)
         */
        photo: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/portal/uploads/photo';
};

export type PostApiV1PortalUploadsPhotoErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Service Unavailable
     */
    503: ModelsAppError;
};

export type PostApiV1PortalUploadsPhotoError = PostApiV1PortalUploadsPhotoErrors[keyof PostApiV1PortalUploadsPhotoErrors];

export type PostApiV1PortalUploadsPhotoResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostApiV1PortalUploadsPhotoResponse = PostApiV1PortalUploadsPhotoResponses[keyof PostApiV1PortalUploadsPhotoResponses];

export type GetApiV1PortalWsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * single-use ticket from POST /api/v1/portal/ws/ticket
         */
        ticket: string;
    };
    url: '/api/v1/portal/ws';
};

export type GetApiV1PortalWsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1PortalWsError = GetApiV1PortalWsErrors[keyof GetApiV1PortalWsErrors];

export type PostApiV1PortalWsTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/ws/ticket';
};

export type PostApiV1PortalWsTicketErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiV1PortalWsTicketError = PostApiV1PortalWsTicketErrors[keyof PostApiV1PortalWsTicketErrors];

export type PostApiV1PortalWsTicketResponses = {
    /**
     * OK
     */
    200: HandlersWsTicketResponse;
};

export type PostApiV1PortalWsTicketResponse = PostApiV1PortalWsTicketResponses[keyof PostApiV1PortalWsTicketResponses];

export type GetApiV1SessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to one client
         */
        client_id?: string;
        /**
         * virtual | inperson | group
         */
        session_type?: string;
        /**
         * RFC3339 lower bound (inclusive)
         */
        from?: string;
        /**
         * RFC3339 upper bound (exclusive)
         */
        to?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/v1/sessions';
};

export type GetApiV1SessionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1SessionsError = GetApiV1SessionsErrors[keyof GetApiV1SessionsErrors];

export type GetApiV1SessionsResponses = {
    /**
     * OK
     */
    200: HandlersListSessionsResponse;
};

export type GetApiV1SessionsResponse = GetApiV1SessionsResponses[keyof GetApiV1SessionsResponses];

export type PostApiV1SessionsData = {
    /**
     * session to create
     */
    body: HandlersCreateSessionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/sessions';
};

export type PostApiV1SessionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * client_id not owned by this coach
     */
    404: ModelsAppError;
};

export type PostApiV1SessionsError = PostApiV1SessionsErrors[keyof PostApiV1SessionsErrors];

export type PostApiV1SessionsResponses = {
    /**
     * Created
     */
    201: ModelsCoachSession;
};

export type PostApiV1SessionsResponse = PostApiV1SessionsResponses[keyof PostApiV1SessionsResponses];

export type DeleteApiV1SessionsByIdData = {
    body?: never;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}';
};

export type DeleteApiV1SessionsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiV1SessionsByIdError = DeleteApiV1SessionsByIdErrors[keyof DeleteApiV1SessionsByIdErrors];

export type DeleteApiV1SessionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiV1SessionsByIdResponse = DeleteApiV1SessionsByIdResponses[keyof DeleteApiV1SessionsByIdResponses];

export type GetApiV1SessionsByIdData = {
    body?: never;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}';
};

export type GetApiV1SessionsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiV1SessionsByIdError = GetApiV1SessionsByIdErrors[keyof GetApiV1SessionsByIdErrors];

export type GetApiV1SessionsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachSession;
};

export type GetApiV1SessionsByIdResponse = GetApiV1SessionsByIdResponses[keyof GetApiV1SessionsByIdResponses];

export type PatchApiV1SessionsByIdData = {
    /**
     * fields to change
     */
    body: HandlersUpdateSessionRequest;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}';
};

export type PatchApiV1SessionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PatchApiV1SessionsByIdError = PatchApiV1SessionsByIdErrors[keyof PatchApiV1SessionsByIdErrors];

export type PatchApiV1SessionsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachSession;
};

export type PatchApiV1SessionsByIdResponse = PatchApiV1SessionsByIdResponses[keyof PatchApiV1SessionsByIdResponses];

export type PostApiV1WebhooksStripeData = {
    body?: never;
    headers: {
        /**
         * Stripe webhook signature
         */
        'Stripe-Signature': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/stripe';
};

export type PostApiV1WebhooksStripeErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
};

export type PostApiV1WebhooksStripeError = PostApiV1WebhooksStripeErrors[keyof PostApiV1WebhooksStripeErrors];

export type PostApiV1WebhooksStripeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1WsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * single-use ticket from POST /api/v1/ws/ticket
         */
        ticket: string;
    };
    url: '/api/v1/ws';
};

export type GetApiV1WsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiV1WsError = GetApiV1WsErrors[keyof GetApiV1WsErrors];

export type PostApiV1WsTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ws/ticket';
};

export type PostApiV1WsTicketErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiV1WsTicketError = PostApiV1WsTicketErrors[keyof PostApiV1WsTicketErrors];

export type PostApiV1WsTicketResponses = {
    /**
     * OK
     */
    200: HandlersWsTicketResponse;
};

export type PostApiV1WsTicketResponse = PostApiV1WsTicketResponses[keyof PostApiV1WsTicketResponses];

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzResponses = {
    /**
     * status: ok
     */
    200: {
        [key: string]: string;
    };
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type GetReadyzErrors = {
    /**
     * status: unready, reason: database unreachable
     */
    503: {
        [key: string]: string;
    };
};

export type GetReadyzError = GetReadyzErrors[keyof GetReadyzErrors];

export type GetReadyzResponses = {
    /**
     * status: ready
     */
    200: {
        [key: string]: string;
    };
};

export type GetReadyzResponse = GetReadyzResponses[keyof GetReadyzResponses];
