// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type HandlersAcceptPortalInviteRequest = {
    password: string;
    token: string;
};

export type HandlersAdvanceOnboardingRequest = {
    step: number;
};

export type HandlersAuthResponse = {
    access_token?: string;
    coach?: ModelsCoach;
    refresh_token?: string;
};

export type HandlersCreateCheckInRequest = {
    energy_score?: number;
    mood_score?: number;
    notes?: string;
    photo_urls?: Array<string>;
    sleep_hrs?: number;
    week_start_date: string;
    weight_lbs?: number;
};

export type HandlersCreateClientRequest = {
    email: string;
    first_name: string;
    goal: string;
    goal_sub?: string;
    last_name: string;
    phone?: string;
    plan_name?: string;
    plan_price_cents?: number;
    program_total?: number;
    program_week?: number;
    start_date: string;
    status?: 'active' | 'paused' | 'new' | 'ended';
};

export type HandlersCreateInvoiceRequest = {
    amount_cents: number;
    client_id?: string;
    /**
     * Currency: any 3-char string. We normalize to lowercase server-side
     * (see below), so a `lowercase` validator tag here would reject the
     * input before normalization could lift it.
     */
    currency?: string;
    description?: string;
    due_date?: string;
};

export type HandlersCreateSessionRequest = {
    client_id?: string;
    confirmed?: boolean;
    duration_mins?: number;
    google_event_id?: string;
    notes?: string;
    session_type: 'virtual' | 'inperson' | 'group';
    starts_at: string;
    title?: string;
    zoom_link?: string;
};

export type HandlersInviteClientPortalResponse = {
    expires_at?: string;
    /**
     * raw; coach's frontend emails this to the client
     */
    invite_token?: string;
    /**
     * ready-to-use deep link to the accept-invite page
     */
    invite_url?: string;
};

export type HandlersListCheckInsResponse = {
    check_ins?: Array<ModelsCoachCheckIn>;
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListClientsResponse = {
    clients?: Array<ModelsClient>;
    /**
     * 1-indexed
     */
    page?: number;
    per_page?: number;
    /**
     * total rows matching filters, ignoring pagination
     */
    total?: number;
    total_pages?: number;
};

export type HandlersListNotificationsResponse = {
    notifications?: Array<ModelsNotification>;
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPaymentsResponse = {
    page?: number;
    payments?: Array<ModelsCoachPayment>;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPortalCheckInsResponse = {
    check_ins?: Array<ModelsCheckIn>;
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPortalPaymentsResponse = {
    page?: number;
    payments?: Array<ModelsPayment>;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type HandlersListPortalSessionsResponse = {
    page?: number;
    per_page?: number;
    sessions?: Array<ModelsSession>;
    total?: number;
    total_pages?: number;
};

export type HandlersListSessionsResponse = {
    page?: number;
    per_page?: number;
    sessions?: Array<ModelsCoachSession>;
    total?: number;
    total_pages?: number;
};

export type HandlersLoginRequest = {
    email: string;
    password: string;
};

export type HandlersLogoutRequest = {
    refresh_token: string;
};

export type HandlersPortalAuthResponse = {
    access_token?: string;
    client_id?: string;
    coach_id?: string;
    email?: string;
    refresh_token?: string;
};

export type HandlersPortalLoginRequest = {
    email: string;
    password: string;
};

export type HandlersPortalLogoutRequest = {
    refresh_token: string;
};

export type HandlersPortalMeResponse = {
    /**
     * Client identity
     */
    client_id?: string;
    coach_avatar?: string;
    /**
     * Coach mini-profile
     */
    coach_id?: string;
    coach_name?: string;
    email?: string;
    first_name?: string;
    /**
     * Program
     */
    goal?: string;
    goal_sub?: string;
    last_name?: string;
    phone?: string;
    plan_name?: string;
    program_total?: number;
    program_week?: number;
    /**
     * YYYY-MM-DD
     */
    start_date?: string;
    status?: string;
};

export type HandlersPortalRefreshRequest = {
    refresh_token: string;
};

export type HandlersRefreshRequest = {
    refresh_token: string;
};

export type HandlersReplaceCustomQuestionsRequest = {
    questions?: Array<ModelsCustomQuestion>;
};

export type HandlersRespondToCheckInRequest = {
    response: string;
};

export type HandlersSaveCheckInDraftRequest = {
    draft?: string;
};

export type HandlersSignupRequest = {
    email: string;
    first_name: string;
    last_name: string;
    password: string;
    specialty: 'personal-training' | 'online-coaching' | 'nutrition' | 'studio';
};

export type HandlersUnreadCountResponse = {
    count?: number;
};

export type HandlersUpdateClientRequest = {
    email?: string;
    first_name?: string;
    goal?: string;
    goal_sub?: string;
    last_name?: string;
    phone?: string;
    plan_name?: string;
    plan_price_cents?: number;
    program_total?: number;
    program_week?: number;
    start_date?: string;
    status?: 'active' | 'paused' | 'new' | 'ended';
};

export type HandlersUpdateMeRequest = {
    avatar_url?: string;
    first_name?: string;
    last_name?: string;
    slug?: string;
    specialty?: 'personal-training' | 'online-coaching' | 'nutrition' | 'studio';
};

export type HandlersUpdateMySettingsRequest = {
    checkin_days?: Array<number>;
    checkin_deadline?: string;
    notif_checkin_new?: boolean;
    notif_checkin_overdue?: boolean;
    notif_checkin_streak?: boolean;
    notif_payment_failed?: boolean;
    notif_payment_received?: boolean;
    notif_schedule_change?: boolean;
    notif_schedule_digest?: boolean;
    reminder_hours?: number;
    timezone?: string;
};

export type HandlersUpdatePaymentRequest = {
    description?: string;
    due_date?: string;
    paid_at?: string;
    sent_at?: string;
    status?: 'paid' | 'pending' | 'failed' | 'overdue' | 'active' | 'cancelling';
};

export type HandlersUpdatePortalMeRequest = {
    phone?: string;
};

export type HandlersUpdateSessionRequest = {
    confirmed?: boolean;
    duration_mins?: number;
    google_event_id?: string;
    notes?: string;
    session_type?: 'virtual' | 'inperson' | 'group';
    starts_at?: string;
    title?: string;
    zoom_link?: string;
};

export type HandlersWsTicketResponse = {
    expires_at?: string;
    ticket?: string;
};

export type ModelsAppError = {
    code?: string;
    error?: string;
};

export type ModelsCheckIn = {
    client_id?: string;
    coach_id?: string;
    coach_response?: string;
    created_at?: string;
    energy_score?: number;
    id?: string;
    is_read?: boolean;
    mood_score?: number;
    notes?: string;
    photo_urls?: Array<string>;
    responded_at?: string;
    sleep_hrs?: number;
    submitted_at?: string;
    /**
     * YYYY-MM-DD (Monday)
     */
    week_start_date?: string;
    weight_lbs?: number;
};

export type ModelsClient = {
    coach_id?: string;
    created_at?: string;
    email?: string;
    first_name?: string;
    goal?: string;
    goal_sub?: string;
    id?: string;
    last_check_in?: string;
    last_name?: string;
    phone?: string;
    plan_name?: string;
    plan_price_cents?: number;
    program_total?: number;
    program_week?: number;
    sessions_count?: number;
    /**
     * YYYY-MM-DD
     */
    start_date?: string;
    status?: string;
    streak_weeks?: number;
    updated_at?: string;
};

export type ModelsCoach = {
    avatar_url?: string;
    created_at?: string;
    email?: string;
    first_name?: string;
    id?: string;
    last_name?: string;
    onboarding_done?: boolean;
    onboarding_step?: number;
    plan?: string;
    plan_seat_limit?: number;
    slug?: string;
    specialty?: string;
    updated_at?: string;
};

export type ModelsCoachCheckIn = {
    client_id?: string;
    coach_id?: string;
    coach_response?: string;
    created_at?: string;
    energy_score?: number;
    id?: string;
    is_read?: boolean;
    mood_score?: number;
    notes?: string;
    photo_urls?: Array<string>;
    responded_at?: string;
    response_draft?: string;
    sleep_hrs?: number;
    submitted_at?: string;
    /**
     * YYYY-MM-DD (Monday)
     */
    week_start_date?: string;
    weight_lbs?: number;
};

export type ModelsCoachPayment = {
    amount_cents?: number;
    client_id?: string;
    coach_id?: string;
    created_at?: string;
    currency?: string;
    description?: string;
    /**
     * YYYY-MM-DD
     */
    due_date?: string;
    id?: string;
    invoice_number?: string;
    /**
     * YYYY-MM-DD
     */
    next_billing_date?: string;
    paid_at?: string;
    payment_type?: string;
    sent_at?: string;
    status?: string;
    stripe_invoice_id?: string;
    stripe_sub_id?: string;
    updated_at?: string;
};

export type ModelsCoachSession = {
    client_id?: string;
    coach_id?: string;
    confirmed?: boolean;
    created_at?: string;
    duration_mins?: number;
    google_event_id?: string;
    id?: string;
    notes?: string;
    session_type?: string;
    starts_at?: string;
    title?: string;
    updated_at?: string;
    zoom_link?: string;
};

export type ModelsCoachSettings = {
    /**
     * 0=Sun .. 6=Sat
     */
    checkin_days?: Array<number>;
    /**
     * "HH:MM" 24h
     */
    checkin_deadline?: string;
    coach_id?: string;
    custom_questions?: Array<ModelsCustomQuestion>;
    notif_checkin_new?: boolean;
    notif_checkin_overdue?: boolean;
    notif_checkin_streak?: boolean;
    notif_payment_failed?: boolean;
    notif_payment_received?: boolean;
    notif_schedule_change?: boolean;
    notif_schedule_digest?: boolean;
    reminder_hours?: number;
    timezone?: string;
    updated_at?: string;
};

export type ModelsCustomQuestion = {
    id: string;
    label: string;
    required?: boolean;
    type: 'text' | 'number' | 'scale' | 'boolean';
};

export type ModelsDashboardStats = {
    active_clients?: number;
    checkins_this_week?: number;
    sessions_today?: number;
    unread_checkins?: number;
};

export type ModelsNotification = {
    created_at?: string;
    /**
     * `swaggertype:"object"` tells swag to document this as an opaque JSON
     * object. The actual Go type is json.RawMessage so the embedded event
     * payload passes through verbatim — the schema is event-type-specific
     * and intentionally polymorphic at the wire level.
     */
    data?: {
        [key: string]: unknown;
    };
    id?: string;
    read_at?: string;
    type?: string;
};

export type ModelsPayment = {
    amount_cents?: number;
    client_id?: string;
    coach_id?: string;
    created_at?: string;
    currency?: string;
    description?: string;
    /**
     * YYYY-MM-DD
     */
    due_date?: string;
    id?: string;
    invoice_number?: string;
    /**
     * YYYY-MM-DD
     */
    next_billing_date?: string;
    paid_at?: string;
    payment_type?: string;
    sent_at?: string;
    status?: string;
    updated_at?: string;
};

export type ModelsSession = {
    client_id?: string;
    coach_id?: string;
    confirmed?: boolean;
    created_at?: string;
    duration_mins?: number;
    id?: string;
    notes?: string;
    session_type?: string;
    starts_at?: string;
    title?: string;
    updated_at?: string;
    zoom_link?: string;
};

export type GetApiAuthGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/google';
};

export type GetApiAuthGoogleErrors = {
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type GetApiAuthGoogleError = GetApiAuthGoogleErrors[keyof GetApiAuthGoogleErrors];

export type GetApiAuthGoogleCallbackData = {
    body?: never;
    path?: never;
    query: {
        /**
         * OAuth state echoed back by Google
         */
        state: string;
        /**
         * OAuth authorization code
         */
        code: string;
    };
    url: '/api/auth/google/callback';
};

export type GetApiAuthGoogleCallbackErrors = {
    /**
     * missing code or state, or state mismatch
     */
    400: ModelsAppError;
    /**
     * google rejected the code
     */
    401: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type GetApiAuthGoogleCallbackError = GetApiAuthGoogleCallbackErrors[keyof GetApiAuthGoogleCallbackErrors];

export type GetApiAuthGoogleCallbackResponses = {
    /**
     * OK
     */
    200: HandlersAuthResponse;
};

export type GetApiAuthGoogleCallbackResponse = GetApiAuthGoogleCallbackResponses[keyof GetApiAuthGoogleCallbackResponses];

export type PostApiAuthLoginData = {
    /**
     * login payload
     */
    body: HandlersLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * validation failed
     */
    400: ModelsAppError;
    /**
     * invalid credentials
     */
    401: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: HandlersAuthResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthLogoutData = {
    /**
     * logout payload
     */
    body: HandlersLogoutRequest;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
};

export type PostApiAuthLogoutError = PostApiAuthLogoutErrors[keyof PostApiAuthLogoutErrors];

export type PostApiAuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAuthLogoutResponse = PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type PostApiAuthRefreshData = {
    /**
     * refresh payload
     */
    body: HandlersRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type PostApiAuthRefreshErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * invalid or revoked refresh token
     */
    401: ModelsAppError;
};

export type PostApiAuthRefreshError = PostApiAuthRefreshErrors[keyof PostApiAuthRefreshErrors];

export type PostApiAuthRefreshResponses = {
    /**
     * OK
     */
    200: HandlersAuthResponse;
};

export type PostApiAuthRefreshResponse = PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type PostApiAuthSignupData = {
    /**
     * signup payload
     */
    body: HandlersSignupRequest;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type PostApiAuthSignupErrors = {
    /**
     * validation failed
     */
    400: ModelsAppError;
    /**
     * email already registered
     */
    409: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiAuthSignupError = PostApiAuthSignupErrors[keyof PostApiAuthSignupErrors];

export type PostApiAuthSignupResponses = {
    /**
     * Created
     */
    201: HandlersAuthResponse;
};

export type PostApiAuthSignupResponse = PostApiAuthSignupResponses[keyof PostApiAuthSignupResponses];

export type GetApiCheckInsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to one client
         */
        client_id?: string;
        /**
         * unread | responded | pending
         */
        status?: string;
        /**
         * YYYY-MM-DD (Monday)
         */
        week_start?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/check-ins';
};

export type GetApiCheckInsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiCheckInsError = GetApiCheckInsErrors[keyof GetApiCheckInsErrors];

export type GetApiCheckInsResponses = {
    /**
     * OK
     */
    200: HandlersListCheckInsResponse;
};

export type GetApiCheckInsResponse = GetApiCheckInsResponses[keyof GetApiCheckInsResponses];

export type GetApiCheckInsByIdData = {
    body?: never;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/check-ins/{id}';
};

export type GetApiCheckInsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiCheckInsByIdError = GetApiCheckInsByIdErrors[keyof GetApiCheckInsByIdErrors];

export type GetApiCheckInsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type GetApiCheckInsByIdResponse = GetApiCheckInsByIdResponses[keyof GetApiCheckInsByIdResponses];

export type PatchApiCheckInsByIdDraftData = {
    /**
     * draft payload
     */
    body: HandlersSaveCheckInDraftRequest;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/check-ins/{id}/draft';
};

export type PatchApiCheckInsByIdDraftErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PatchApiCheckInsByIdDraftError = PatchApiCheckInsByIdDraftErrors[keyof PatchApiCheckInsByIdDraftErrors];

export type PatchApiCheckInsByIdDraftResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type PatchApiCheckInsByIdDraftResponse = PatchApiCheckInsByIdDraftResponses[keyof PatchApiCheckInsByIdDraftResponses];

export type PostApiCheckInsByIdReadData = {
    body?: never;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/check-ins/{id}/read';
};

export type PostApiCheckInsByIdReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiCheckInsByIdReadError = PostApiCheckInsByIdReadErrors[keyof PostApiCheckInsByIdReadErrors];

export type PostApiCheckInsByIdReadResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type PostApiCheckInsByIdReadResponse = PostApiCheckInsByIdReadResponses[keyof PostApiCheckInsByIdReadResponses];

export type PostApiCheckInsByIdRespondData = {
    /**
     * response payload
     */
    body: HandlersRespondToCheckInRequest;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/check-ins/{id}/respond';
};

export type PostApiCheckInsByIdRespondErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiCheckInsByIdRespondError = PostApiCheckInsByIdRespondErrors[keyof PostApiCheckInsByIdRespondErrors];

export type PostApiCheckInsByIdRespondResponses = {
    /**
     * OK
     */
    200: ModelsCoachCheckIn;
};

export type PostApiCheckInsByIdRespondResponse = PostApiCheckInsByIdRespondResponses[keyof PostApiCheckInsByIdRespondResponses];

export type GetApiClientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * active | paused | new | ended
         */
        status?: string;
        /**
         * substring match on name or email
         */
        search?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/clients';
};

export type GetApiClientsErrors = {
    /**
     * invalid query params
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type GetApiClientsError = GetApiClientsErrors[keyof GetApiClientsErrors];

export type GetApiClientsResponses = {
    /**
     * OK
     */
    200: HandlersListClientsResponse;
};

export type GetApiClientsResponse = GetApiClientsResponses[keyof GetApiClientsResponses];

export type PostApiClientsData = {
    /**
     * client to create
     */
    body: HandlersCreateClientRequest;
    path?: never;
    query?: never;
    url: '/api/clients';
};

export type PostApiClientsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * email already in use for this coach
     */
    409: ModelsAppError;
};

export type PostApiClientsError = PostApiClientsErrors[keyof PostApiClientsErrors];

export type PostApiClientsResponses = {
    /**
     * Created
     */
    201: ModelsClient;
};

export type PostApiClientsResponse = PostApiClientsResponses[keyof PostApiClientsResponses];

export type DeleteApiClientsByIdData = {
    body?: never;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/clients/{id}';
};

export type DeleteApiClientsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiClientsByIdError = DeleteApiClientsByIdErrors[keyof DeleteApiClientsByIdErrors];

export type DeleteApiClientsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiClientsByIdResponse = DeleteApiClientsByIdResponses[keyof DeleteApiClientsByIdResponses];

export type GetApiClientsByIdData = {
    body?: never;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/clients/{id}';
};

export type GetApiClientsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiClientsByIdError = GetApiClientsByIdErrors[keyof GetApiClientsByIdErrors];

export type GetApiClientsByIdResponses = {
    /**
     * OK
     */
    200: ModelsClient;
};

export type GetApiClientsByIdResponse = GetApiClientsByIdResponses[keyof GetApiClientsByIdResponses];

export type PatchApiClientsByIdData = {
    /**
     * fields to change
     */
    body: HandlersUpdateClientRequest;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/clients/{id}';
};

export type PatchApiClientsByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
    /**
     * Conflict
     */
    409: ModelsAppError;
};

export type PatchApiClientsByIdError = PatchApiClientsByIdErrors[keyof PatchApiClientsByIdErrors];

export type PatchApiClientsByIdResponses = {
    /**
     * OK
     */
    200: ModelsClient;
};

export type PatchApiClientsByIdResponse = PatchApiClientsByIdResponses[keyof PatchApiClientsByIdResponses];

export type PostApiClientsByIdInvitePortalData = {
    body?: never;
    path: {
        /**
         * client UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/clients/{id}/invite-portal';
};

export type PostApiClientsByIdInvitePortalErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiClientsByIdInvitePortalError = PostApiClientsByIdInvitePortalErrors[keyof PostApiClientsByIdInvitePortalErrors];

export type PostApiClientsByIdInvitePortalResponses = {
    /**
     * OK
     */
    200: HandlersInviteClientPortalResponse;
};

export type PostApiClientsByIdInvitePortalResponse = PostApiClientsByIdInvitePortalResponses[keyof PostApiClientsByIdInvitePortalResponses];

export type GetApiMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetApiMeErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiMeError = GetApiMeErrors[keyof GetApiMeErrors];

export type GetApiMeResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type GetApiMeResponse = GetApiMeResponses[keyof GetApiMeResponses];

export type PatchApiMeData = {
    /**
     * fields to change
     */
    body: HandlersUpdateMeRequest;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type PatchApiMeErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * slug already in use
     */
    409: ModelsAppError;
};

export type PatchApiMeError = PatchApiMeErrors[keyof PatchApiMeErrors];

export type PatchApiMeResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type PatchApiMeResponse = PatchApiMeResponses[keyof PatchApiMeResponses];

export type PostApiMeAvatarData = {
    body: {
        /**
         * Image file (JPEG/PNG/WEBP, max 4 MB)
         */
        avatar: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/me/avatar';
};

export type PostApiMeAvatarErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Service Unavailable
     */
    503: ModelsAppError;
};

export type PostApiMeAvatarError = PostApiMeAvatarErrors[keyof PostApiMeAvatarErrors];

export type PostApiMeAvatarResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type PostApiMeAvatarResponse = PostApiMeAvatarResponses[keyof PostApiMeAvatarResponses];

export type GetApiMeDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/dashboard';
};

export type GetApiMeDashboardErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiMeDashboardError = GetApiMeDashboardErrors[keyof GetApiMeDashboardErrors];

export type GetApiMeDashboardResponses = {
    /**
     * OK
     */
    200: ModelsDashboardStats;
};

export type GetApiMeDashboardResponse = GetApiMeDashboardResponses[keyof GetApiMeDashboardResponses];

export type PatchApiMeOnboardingData = {
    /**
     * step payload
     */
    body: HandlersAdvanceOnboardingRequest;
    path?: never;
    query?: never;
    url: '/api/me/onboarding';
};

export type PatchApiMeOnboardingErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PatchApiMeOnboardingError = PatchApiMeOnboardingErrors[keyof PatchApiMeOnboardingErrors];

export type PatchApiMeOnboardingResponses = {
    /**
     * OK
     */
    200: ModelsCoach;
};

export type PatchApiMeOnboardingResponse = PatchApiMeOnboardingResponses[keyof PatchApiMeOnboardingResponses];

export type GetApiMeSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/settings';
};

export type GetApiMeSettingsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiMeSettingsError = GetApiMeSettingsErrors[keyof GetApiMeSettingsErrors];

export type GetApiMeSettingsResponses = {
    /**
     * OK
     */
    200: ModelsCoachSettings;
};

export type GetApiMeSettingsResponse = GetApiMeSettingsResponses[keyof GetApiMeSettingsResponses];

export type PatchApiMeSettingsData = {
    /**
     * fields to change
     */
    body: HandlersUpdateMySettingsRequest;
    path?: never;
    query?: never;
    url: '/api/me/settings';
};

export type PatchApiMeSettingsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PatchApiMeSettingsError = PatchApiMeSettingsErrors[keyof PatchApiMeSettingsErrors];

export type PatchApiMeSettingsResponses = {
    /**
     * OK
     */
    200: ModelsCoachSettings;
};

export type PatchApiMeSettingsResponse = PatchApiMeSettingsResponses[keyof PatchApiMeSettingsResponses];

export type PutApiMeSettingsCustomQuestionsData = {
    /**
     * questions array
     */
    body: HandlersReplaceCustomQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/me/settings/custom-questions';
};

export type PutApiMeSettingsCustomQuestionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PutApiMeSettingsCustomQuestionsError = PutApiMeSettingsCustomQuestionsErrors[keyof PutApiMeSettingsCustomQuestionsErrors];

export type PutApiMeSettingsCustomQuestionsResponses = {
    /**
     * OK
     */
    200: ModelsCoachSettings;
};

export type PutApiMeSettingsCustomQuestionsResponse = PutApiMeSettingsCustomQuestionsResponses[keyof PutApiMeSettingsCustomQuestionsResponses];

export type GetApiNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to unread only
         */
        unread?: boolean;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/notifications';
};

export type GetApiNotificationsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiNotificationsError = GetApiNotificationsErrors[keyof GetApiNotificationsErrors];

export type GetApiNotificationsResponses = {
    /**
     * OK
     */
    200: HandlersListNotificationsResponse;
};

export type GetApiNotificationsResponse = GetApiNotificationsResponses[keyof GetApiNotificationsResponses];

export type PostApiNotificationsMarkAllReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/mark-all-read';
};

export type PostApiNotificationsMarkAllReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiNotificationsMarkAllReadError = PostApiNotificationsMarkAllReadErrors[keyof PostApiNotificationsMarkAllReadErrors];

export type PostApiNotificationsMarkAllReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiNotificationsMarkAllReadResponse = PostApiNotificationsMarkAllReadResponses[keyof PostApiNotificationsMarkAllReadResponses];

export type GetApiNotificationsUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/unread-count';
};

export type GetApiNotificationsUnreadCountErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiNotificationsUnreadCountError = GetApiNotificationsUnreadCountErrors[keyof GetApiNotificationsUnreadCountErrors];

export type GetApiNotificationsUnreadCountResponses = {
    /**
     * OK
     */
    200: HandlersUnreadCountResponse;
};

export type GetApiNotificationsUnreadCountResponse = GetApiNotificationsUnreadCountResponses[keyof GetApiNotificationsUnreadCountResponses];

export type DeleteApiNotificationsByIdData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/notifications/{id}';
};

export type DeleteApiNotificationsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiNotificationsByIdError = DeleteApiNotificationsByIdErrors[keyof DeleteApiNotificationsByIdErrors];

export type DeleteApiNotificationsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiNotificationsByIdResponse = DeleteApiNotificationsByIdResponses[keyof DeleteApiNotificationsByIdResponses];

export type PostApiNotificationsByIdReadData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/notifications/{id}/read';
};

export type PostApiNotificationsByIdReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiNotificationsByIdReadError = PostApiNotificationsByIdReadErrors[keyof PostApiNotificationsByIdReadErrors];

export type PostApiNotificationsByIdReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiNotificationsByIdReadResponse = PostApiNotificationsByIdReadResponses[keyof PostApiNotificationsByIdReadResponses];

export type GetApiPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to one client
         */
        client_id?: string;
        /**
         * invoice | subscription
         */
        payment_type?: string;
        /**
         * paid | pending | failed | overdue | active | cancelling
         */
        status?: string;
        /**
         * RFC3339 lower bound (inclusive)
         */
        from?: string;
        /**
         * RFC3339 upper bound (exclusive)
         */
        to?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/payments';
};

export type GetApiPaymentsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiPaymentsError = GetApiPaymentsErrors[keyof GetApiPaymentsErrors];

export type GetApiPaymentsResponses = {
    /**
     * OK
     */
    200: HandlersListPaymentsResponse;
};

export type GetApiPaymentsResponse = GetApiPaymentsResponses[keyof GetApiPaymentsResponses];

export type PostApiPaymentsData = {
    /**
     * invoice to create
     */
    body: HandlersCreateInvoiceRequest;
    path?: never;
    query?: never;
    url: '/api/payments';
};

export type PostApiPaymentsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * client_id not owned by this coach
     */
    404: ModelsAppError;
};

export type PostApiPaymentsError = PostApiPaymentsErrors[keyof PostApiPaymentsErrors];

export type PostApiPaymentsResponses = {
    /**
     * Created
     */
    201: ModelsCoachPayment;
};

export type PostApiPaymentsResponse = PostApiPaymentsResponses[keyof PostApiPaymentsResponses];

export type GetApiPaymentsByIdData = {
    body?: never;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/payments/{id}';
};

export type GetApiPaymentsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiPaymentsByIdError = GetApiPaymentsByIdErrors[keyof GetApiPaymentsByIdErrors];

export type GetApiPaymentsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachPayment;
};

export type GetApiPaymentsByIdResponse = GetApiPaymentsByIdResponses[keyof GetApiPaymentsByIdResponses];

export type PatchApiPaymentsByIdData = {
    /**
     * fields to change
     */
    body: HandlersUpdatePaymentRequest;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/payments/{id}';
};

export type PatchApiPaymentsByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PatchApiPaymentsByIdError = PatchApiPaymentsByIdErrors[keyof PatchApiPaymentsByIdErrors];

export type PatchApiPaymentsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachPayment;
};

export type PatchApiPaymentsByIdResponse = PatchApiPaymentsByIdResponses[keyof PatchApiPaymentsByIdResponses];

export type PostApiPaymentsByIdMarkPaidData = {
    body?: never;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/payments/{id}/mark-paid';
};

export type PostApiPaymentsByIdMarkPaidErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiPaymentsByIdMarkPaidError = PostApiPaymentsByIdMarkPaidErrors[keyof PostApiPaymentsByIdMarkPaidErrors];

export type PostApiPaymentsByIdMarkPaidResponses = {
    /**
     * OK
     */
    200: ModelsCoachPayment;
};

export type PostApiPaymentsByIdMarkPaidResponse = PostApiPaymentsByIdMarkPaidResponses[keyof PostApiPaymentsByIdMarkPaidResponses];

export type PostApiPortalAcceptInviteData = {
    /**
     * accept invite payload
     */
    body: HandlersAcceptPortalInviteRequest;
    path?: never;
    query?: never;
    url: '/api/portal/accept-invite';
};

export type PostApiPortalAcceptInviteErrors = {
    /**
     * invalid token, expired, or weak password
     */
    400: ModelsAppError;
    /**
     * Internal Server Error
     */
    500: ModelsAppError;
};

export type PostApiPortalAcceptInviteError = PostApiPortalAcceptInviteErrors[keyof PostApiPortalAcceptInviteErrors];

export type PostApiPortalAcceptInviteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPortalAcceptInviteResponse = PostApiPortalAcceptInviteResponses[keyof PostApiPortalAcceptInviteResponses];

export type PostApiPortalAuthLoginData = {
    /**
     * login payload
     */
    body: HandlersPortalLoginRequest;
    path?: never;
    query?: never;
    url: '/api/portal/auth/login';
};

export type PostApiPortalAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * invalid credentials
     */
    401: ModelsAppError;
};

export type PostApiPortalAuthLoginError = PostApiPortalAuthLoginErrors[keyof PostApiPortalAuthLoginErrors];

export type PostApiPortalAuthLoginResponses = {
    /**
     * OK
     */
    200: HandlersPortalAuthResponse;
};

export type PostApiPortalAuthLoginResponse = PostApiPortalAuthLoginResponses[keyof PostApiPortalAuthLoginResponses];

export type PostApiPortalAuthLogoutData = {
    /**
     * logout payload
     */
    body: HandlersPortalLogoutRequest;
    path?: never;
    query?: never;
    url: '/api/portal/auth/logout';
};

export type PostApiPortalAuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
};

export type PostApiPortalAuthLogoutError = PostApiPortalAuthLogoutErrors[keyof PostApiPortalAuthLogoutErrors];

export type PostApiPortalAuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPortalAuthLogoutResponse = PostApiPortalAuthLogoutResponses[keyof PostApiPortalAuthLogoutResponses];

export type PostApiPortalAuthRefreshData = {
    /**
     * refresh payload
     */
    body: HandlersPortalRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/portal/auth/refresh';
};

export type PostApiPortalAuthRefreshErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiPortalAuthRefreshError = PostApiPortalAuthRefreshErrors[keyof PostApiPortalAuthRefreshErrors];

export type PostApiPortalAuthRefreshResponses = {
    /**
     * OK
     */
    200: HandlersPortalAuthResponse;
};

export type PostApiPortalAuthRefreshResponse = PostApiPortalAuthRefreshResponses[keyof PostApiPortalAuthRefreshResponses];

export type GetApiPortalCheckInsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/portal/check-ins';
};

export type GetApiPortalCheckInsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiPortalCheckInsError = GetApiPortalCheckInsErrors[keyof GetApiPortalCheckInsErrors];

export type GetApiPortalCheckInsResponses = {
    /**
     * OK
     */
    200: HandlersListPortalCheckInsResponse;
};

export type GetApiPortalCheckInsResponse = GetApiPortalCheckInsResponses[keyof GetApiPortalCheckInsResponses];

export type PostApiPortalCheckInsData = {
    /**
     * check-in payload
     */
    body: HandlersCreateCheckInRequest;
    path?: never;
    query?: never;
    url: '/api/portal/check-ins';
};

export type PostApiPortalCheckInsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * check-in for this week already exists
     */
    409: ModelsAppError;
};

export type PostApiPortalCheckInsError = PostApiPortalCheckInsErrors[keyof PostApiPortalCheckInsErrors];

export type PostApiPortalCheckInsResponses = {
    /**
     * Created
     */
    201: ModelsCheckIn;
};

export type PostApiPortalCheckInsResponse = PostApiPortalCheckInsResponses[keyof PostApiPortalCheckInsResponses];

export type GetApiPortalCheckInsByIdData = {
    body?: never;
    path: {
        /**
         * check-in UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/portal/check-ins/{id}';
};

export type GetApiPortalCheckInsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiPortalCheckInsByIdError = GetApiPortalCheckInsByIdErrors[keyof GetApiPortalCheckInsByIdErrors];

export type GetApiPortalCheckInsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCheckIn;
};

export type GetApiPortalCheckInsByIdResponse = GetApiPortalCheckInsByIdResponses[keyof GetApiPortalCheckInsByIdResponses];

export type GetApiPortalMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portal/me';
};

export type GetApiPortalMeErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiPortalMeError = GetApiPortalMeErrors[keyof GetApiPortalMeErrors];

export type GetApiPortalMeResponses = {
    /**
     * OK
     */
    200: HandlersPortalMeResponse;
};

export type GetApiPortalMeResponse = GetApiPortalMeResponses[keyof GetApiPortalMeResponses];

export type PatchApiPortalMeData = {
    /**
     * fields to update
     */
    body: HandlersUpdatePortalMeRequest;
    path?: never;
    query?: never;
    url: '/api/portal/me';
};

export type PatchApiPortalMeErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PatchApiPortalMeError = PatchApiPortalMeErrors[keyof PatchApiPortalMeErrors];

export type PatchApiPortalMeResponses = {
    /**
     * OK
     */
    200: HandlersPortalMeResponse;
};

export type PatchApiPortalMeResponse = PatchApiPortalMeResponses[keyof PatchApiPortalMeResponses];

export type GetApiPortalNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to unread only
         */
        unread?: boolean;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/portal/notifications';
};

export type GetApiPortalNotificationsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiPortalNotificationsError = GetApiPortalNotificationsErrors[keyof GetApiPortalNotificationsErrors];

export type GetApiPortalNotificationsResponses = {
    /**
     * OK
     */
    200: HandlersListNotificationsResponse;
};

export type GetApiPortalNotificationsResponse = GetApiPortalNotificationsResponses[keyof GetApiPortalNotificationsResponses];

export type PostApiPortalNotificationsMarkAllReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portal/notifications/mark-all-read';
};

export type PostApiPortalNotificationsMarkAllReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiPortalNotificationsMarkAllReadError = PostApiPortalNotificationsMarkAllReadErrors[keyof PostApiPortalNotificationsMarkAllReadErrors];

export type PostApiPortalNotificationsMarkAllReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPortalNotificationsMarkAllReadResponse = PostApiPortalNotificationsMarkAllReadResponses[keyof PostApiPortalNotificationsMarkAllReadResponses];

export type GetApiPortalNotificationsUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portal/notifications/unread-count';
};

export type GetApiPortalNotificationsUnreadCountErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiPortalNotificationsUnreadCountError = GetApiPortalNotificationsUnreadCountErrors[keyof GetApiPortalNotificationsUnreadCountErrors];

export type GetApiPortalNotificationsUnreadCountResponses = {
    /**
     * OK
     */
    200: HandlersUnreadCountResponse;
};

export type GetApiPortalNotificationsUnreadCountResponse = GetApiPortalNotificationsUnreadCountResponses[keyof GetApiPortalNotificationsUnreadCountResponses];

export type DeleteApiPortalNotificationsByIdData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/portal/notifications/{id}';
};

export type DeleteApiPortalNotificationsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiPortalNotificationsByIdError = DeleteApiPortalNotificationsByIdErrors[keyof DeleteApiPortalNotificationsByIdErrors];

export type DeleteApiPortalNotificationsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortalNotificationsByIdResponse = DeleteApiPortalNotificationsByIdResponses[keyof DeleteApiPortalNotificationsByIdResponses];

export type PostApiPortalNotificationsByIdReadData = {
    body?: never;
    path: {
        /**
         * notification UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/portal/notifications/{id}/read';
};

export type PostApiPortalNotificationsByIdReadErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PostApiPortalNotificationsByIdReadError = PostApiPortalNotificationsByIdReadErrors[keyof PostApiPortalNotificationsByIdReadErrors];

export type PostApiPortalNotificationsByIdReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiPortalNotificationsByIdReadResponse = PostApiPortalNotificationsByIdReadResponses[keyof PostApiPortalNotificationsByIdReadResponses];

export type GetApiPortalPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/portal/payments';
};

export type GetApiPortalPaymentsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiPortalPaymentsError = GetApiPortalPaymentsErrors[keyof GetApiPortalPaymentsErrors];

export type GetApiPortalPaymentsResponses = {
    /**
     * OK
     */
    200: HandlersListPortalPaymentsResponse;
};

export type GetApiPortalPaymentsResponse = GetApiPortalPaymentsResponses[keyof GetApiPortalPaymentsResponses];

export type GetApiPortalPaymentsByIdData = {
    body?: never;
    path: {
        /**
         * payment UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/portal/payments/{id}';
};

export type GetApiPortalPaymentsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiPortalPaymentsByIdError = GetApiPortalPaymentsByIdErrors[keyof GetApiPortalPaymentsByIdErrors];

export type GetApiPortalPaymentsByIdResponses = {
    /**
     * OK
     */
    200: ModelsPayment;
};

export type GetApiPortalPaymentsByIdResponse = GetApiPortalPaymentsByIdResponses[keyof GetApiPortalPaymentsByIdResponses];

export type GetApiPortalSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * RFC3339 lower bound (inclusive)
         */
        from?: string;
        /**
         * RFC3339 upper bound (exclusive)
         */
        to?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/portal/sessions';
};

export type GetApiPortalSessionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiPortalSessionsError = GetApiPortalSessionsErrors[keyof GetApiPortalSessionsErrors];

export type GetApiPortalSessionsResponses = {
    /**
     * OK
     */
    200: HandlersListPortalSessionsResponse;
};

export type GetApiPortalSessionsResponse = GetApiPortalSessionsResponses[keyof GetApiPortalSessionsResponses];

export type GetApiPortalSessionsByIdData = {
    body?: never;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/portal/sessions/{id}';
};

export type GetApiPortalSessionsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiPortalSessionsByIdError = GetApiPortalSessionsByIdErrors[keyof GetApiPortalSessionsByIdErrors];

export type GetApiPortalSessionsByIdResponses = {
    /**
     * OK
     */
    200: ModelsSession;
};

export type GetApiPortalSessionsByIdResponse = GetApiPortalSessionsByIdResponses[keyof GetApiPortalSessionsByIdResponses];

export type PostApiPortalUploadsPhotoData = {
    body: {
        /**
         * Image file (JPEG/PNG/WEBP, max 4 MB)
         */
        photo: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/portal/uploads/photo';
};

export type PostApiPortalUploadsPhotoErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Service Unavailable
     */
    503: ModelsAppError;
};

export type PostApiPortalUploadsPhotoError = PostApiPortalUploadsPhotoErrors[keyof PostApiPortalUploadsPhotoErrors];

export type PostApiPortalUploadsPhotoResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostApiPortalUploadsPhotoResponse = PostApiPortalUploadsPhotoResponses[keyof PostApiPortalUploadsPhotoResponses];

export type GetApiPortalWsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * single-use ticket from POST /api/portal/ws/ticket
         */
        ticket: string;
    };
    url: '/api/portal/ws';
};

export type GetApiPortalWsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiPortalWsError = GetApiPortalWsErrors[keyof GetApiPortalWsErrors];

export type PostApiPortalWsTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portal/ws/ticket';
};

export type PostApiPortalWsTicketErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiPortalWsTicketError = PostApiPortalWsTicketErrors[keyof PostApiPortalWsTicketErrors];

export type PostApiPortalWsTicketResponses = {
    /**
     * OK
     */
    200: HandlersWsTicketResponse;
};

export type PostApiPortalWsTicketResponse = PostApiPortalWsTicketResponses[keyof PostApiPortalWsTicketResponses];

export type GetApiSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * filter to one client
         */
        client_id?: string;
        /**
         * virtual | inperson | group
         */
        session_type?: string;
        /**
         * RFC3339 lower bound (inclusive)
         */
        from?: string;
        /**
         * RFC3339 upper bound (exclusive)
         */
        to?: string;
        /**
         * 1-indexed page (default 1)
         */
        page?: number;
        /**
         * page size (default 20, max 100)
         */
        per_page?: number;
    };
    url: '/api/sessions';
};

export type GetApiSessionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiSessionsError = GetApiSessionsErrors[keyof GetApiSessionsErrors];

export type GetApiSessionsResponses = {
    /**
     * OK
     */
    200: HandlersListSessionsResponse;
};

export type GetApiSessionsResponse = GetApiSessionsResponses[keyof GetApiSessionsResponses];

export type PostApiSessionsData = {
    /**
     * session to create
     */
    body: HandlersCreateSessionRequest;
    path?: never;
    query?: never;
    url: '/api/sessions';
};

export type PostApiSessionsErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * client_id not owned by this coach
     */
    404: ModelsAppError;
};

export type PostApiSessionsError = PostApiSessionsErrors[keyof PostApiSessionsErrors];

export type PostApiSessionsResponses = {
    /**
     * Created
     */
    201: ModelsCoachSession;
};

export type PostApiSessionsResponse = PostApiSessionsResponses[keyof PostApiSessionsResponses];

export type DeleteApiSessionsByIdData = {
    body?: never;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}';
};

export type DeleteApiSessionsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type DeleteApiSessionsByIdError = DeleteApiSessionsByIdErrors[keyof DeleteApiSessionsByIdErrors];

export type DeleteApiSessionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiSessionsByIdResponse = DeleteApiSessionsByIdResponses[keyof DeleteApiSessionsByIdResponses];

export type GetApiSessionsByIdData = {
    body?: never;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}';
};

export type GetApiSessionsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type GetApiSessionsByIdError = GetApiSessionsByIdErrors[keyof GetApiSessionsByIdErrors];

export type GetApiSessionsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachSession;
};

export type GetApiSessionsByIdResponse = GetApiSessionsByIdResponses[keyof GetApiSessionsByIdResponses];

export type PatchApiSessionsByIdData = {
    /**
     * fields to change
     */
    body: HandlersUpdateSessionRequest;
    path: {
        /**
         * session UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}';
};

export type PatchApiSessionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
    /**
     * Unauthorized
     */
    401: ModelsAppError;
    /**
     * Not Found
     */
    404: ModelsAppError;
};

export type PatchApiSessionsByIdError = PatchApiSessionsByIdErrors[keyof PatchApiSessionsByIdErrors];

export type PatchApiSessionsByIdResponses = {
    /**
     * OK
     */
    200: ModelsCoachSession;
};

export type PatchApiSessionsByIdResponse = PatchApiSessionsByIdResponses[keyof PatchApiSessionsByIdResponses];

export type PostApiWebhooksStripeData = {
    body?: never;
    headers: {
        /**
         * Stripe webhook signature
         */
        'Stripe-Signature': string;
    };
    path?: never;
    query?: never;
    url: '/api/webhooks/stripe';
};

export type PostApiWebhooksStripeErrors = {
    /**
     * Bad Request
     */
    400: ModelsAppError;
};

export type PostApiWebhooksStripeError = PostApiWebhooksStripeErrors[keyof PostApiWebhooksStripeErrors];

export type PostApiWebhooksStripeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiWsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * single-use ticket from POST /api/ws/ticket
         */
        ticket: string;
    };
    url: '/api/ws';
};

export type GetApiWsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type GetApiWsError = GetApiWsErrors[keyof GetApiWsErrors];

export type PostApiWsTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ws/ticket';
};

export type PostApiWsTicketErrors = {
    /**
     * Unauthorized
     */
    401: ModelsAppError;
};

export type PostApiWsTicketError = PostApiWsTicketErrors[keyof PostApiWsTicketErrors];

export type PostApiWsTicketResponses = {
    /**
     * OK
     */
    200: HandlersWsTicketResponse;
};

export type PostApiWsTicketResponse = PostApiWsTicketResponses[keyof PostApiWsTicketResponses];

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzResponses = {
    /**
     * status: ok
     */
    200: {
        [key: string]: string;
    };
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type GetReadyzErrors = {
    /**
     * status: unready, reason: database unreachable
     */
    503: {
        [key: string]: string;
    };
};

export type GetReadyzError = GetReadyzErrors[keyof GetReadyzErrors];

export type GetReadyzResponses = {
    /**
     * status: ready
     */
    200: {
        [key: string]: string;
    };
};

export type GetReadyzResponse = GetReadyzResponses[keyof GetReadyzResponses];
